### ISSUE TITLE
Add logic to remove v from inputs

### ISSUE THREAD

**Issue by duffney** [Duffney/setup-notation#5]
Adding a `v` in front of the version number is a common mistake made by people using the action. To improve the user experience add logic that handles the additional v by checking if a v exists within the version number and removing it before passing to the URL to download. 

Example: Allow this to work

```
    - name: Setup Notation with azure-kv plugin
      uses: Duffney/setup-notation@v0.12.0
      with:
        version: v1.0.0-rc.1
        key_name: ${{ inputs.certName }}
        certificate_key_id: ${{ steps.kid.outputs.SIGN_CERT_KEY_ID }}
        plugin_name: notation-azure-kv
        plugin_version: v0.5.0-rc.1
```
