### ISSUE TITLE
Signing provides Unauthorized error.

### ISSUE THREAD

**Issue by Miranlfk** [Duffney/setup-notation#6]
$title

I'm running a workflow to sign an image via test keys, Login to the registry is done successfully, key is generated and the generated key is verified via `notation key ls` however, during the signing job, it provides a unauthorized(401) error.

**Comment by duffney** [comment]
Hey @Miranlfk, do you mind sharing with me the `notation sign` command you're running? You might also need to provide the `--username` and `--password` args in addition to the registry sign in.

**Comment by Miranlfk** [comment]
Hi, my sign command is as follows:

```
- name: Sign the published Docker image
        env: 
          password: ${{ secrets.GITHUB_TOKEN }}
        run: notation sign ${{ env.REGISTRY }}/miranlfk/${{ env.IMAGE_NAME }}:v${{ github.run_number }}
```
I generated a test key and verified prior to signing here too as follows:

```
- name: Generate key to sign published Docker image
        run: notation cert generate-test --default "trusted" 
        
      - name: Verify key generation
        run: notation key list 

```
