### ISSUE TITLE
Signing via key from Azure-keyvault does not get executed

### ISSUE THREAD

**Issue by Miranlfk** [Duffney/setup-notation#7]
$title 
I'm running a workflow to sign an image via Azure-keyvault keys, Login to the Github registry is done successfully, Login to Azure is done successfully, The key in the Azure key vault is accessed and is verified via notation key ls however, during the signing job, it does not execute the signing job and sign the image in the github package.  The following workflow file is as follows:

```
name: publish
on: [push]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: bal-test-notation

jobs:
  publish-Ballerina-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: azure-resource-login
        uses: Azure/azure-resource-login-action@v1.0.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Setup Notation with azure-kv plugin
        uses: Duffney/setup-notation@v1.0.0
        with:
          version: 1.0.0-rc.7
          key_name: balkeyazure
          certificate_key_id: https://balkey.vault.azure.net/keys/xxxxxx/xxxxxxxxxxxxxxxxxxxxxxx
          plugin_name: notation-azure-kv
          plugin_version:  0.5.0-rc.1
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Ballerina Docker image
        run: |

          docker build --no-cache=true . --tag ${{ env.REGISTRY }}/miranlfk/${{ env.IMAGE_NAME }}:v${{ github.run_number }}
          docker run ${{ env.REGISTRY }}/miranlfk/${{ env.IMAGE_NAME }}:v${{ github.run_number }}
          docker push ${{ env.REGISTRY }}/miranlfk/${{ env.IMAGE_NAME }}:v${{ github.run_number }}

      - name: Verify key generation
        run: notation key list 
     
      - name: Sign the published Docker image
        env: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          password: ${{ secrets.GITHUB_TOKEN }}
        run: notation sign ${{ env.REGISTRY }}/miranlfk/${{ env.IMAGE_NAME }}:v${{ github.run_number }}
```

Here is an image for reference:
![11](https://github.com/Duffney/setup-notation/assets/85722530/2a90fef6-c291-4b92-99eb-97e48088d533)
